### ISSUE TITLE
Dapper.UnitOfWork

### ISSUE THREAD

**Issue by ghost** [outmatic/Dapper.UnitOfWork#2]
Does Dapper.UnitOfWork support NETCORE?

**Comment by petrhaus** [comment]
Sorry for the late reply, but for some reason I'm not receiving notifications from Github.
Actually there is no support for .net core but I'm going to add it in the next few days, as I need to port some projects to .net core as well.

**Comment by petrhaus** [comment]
The latest commit (https://github.com/outmatic/Dapper.UnitOfWork/commit/79f7493cd482d5828916c311893ae2e56f880dec) targets .net standard, therefore you should be able to use it in your .net core projects.

**Comment by ghost** [comment]
This is terrific
