### ISSUE TITLE
Creating UoW for postgres connection.

### ISSUE THREAD

**Issue by dnnedelchev** [outmatic/Dapper.UnitOfWork#7]
Is it possible to create a IDbConnection with npgsql connection so that it can be used with postgres db?

**Comment by petrhaus** [comment]
Sorry for the late reply, but I was on holiday.
It should be possible, but it may require some breaking changes.
If you want to contribute and open a pull request it would be very nice, otherwise I will try to look into it in the coming weeks.

**Comment by petrhaus** [comment]
I've published to nuget a beta version (https://www.nuget.org/packages/Dapper.UnitOfWork/1.7.0-beta) which allows you to pass in a DbProviderFactory, in your case it should be NpgsqlFactory.Instance.

```
        public UnitOfWorkFactory(string connectionString, DbProviderFactory dbProviderFactory = null)
        {
            _connectionString = connectionString;
            _dbProviderFactory = dbProviderFactory ?? SqlClientFactory.Instance;
        }
```

Please let me know if it works, so I can finalize version 1.7.0

**Comment by petrhaus** [comment]
Hi @dnnedelchev,
your feedback would be highly appreciated...

Thanks.
